name: Tests with Jest and Coverage

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: yarn ci

      - name: Executar testes Jest e gerar coverage
        run: yarn test

      - name: Upload do relatório de coverage
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-de-codigo
          path: coverage/
